FROM python:3.10-slim

WORKDIR /app

# Установи зависимости
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Скопируй requirements
COPY inforadar_parser/requirements.txt .

# Установи пакеты
RUN pip install --no-cache-dir -r requirements.txt

# Скопируй код парсера
COPY inforadar_parser/arbitrage-detector.py .

# Запусти парсер
CMD ["python3", "arbitrage-detector.py"]
